### ISSUE TITLE
Game does not start from cmd

### ISSUE THREAD

**Issue by 1kastner** [jemboy/knowledge-invasion#1]
When I start the game, I get the following output:

===cmd.exe===
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\marvin>python C:\Users\marvin\Downloads\knowledge-invasion-master\knowl
edge-invasion-master\main.py
Traceback (most recent call last):
  File "C:\Users\marvin\Downloads\knowledge-invasion-master\knowledge-invasion-m
aster\main.py", line 3, in <module>
    from countryselector import CountrySelector
ImportError: No module named countryselector

C:\Users\marvin>

**Comment by jemboy** [comment]
I deleted a file by accident. It should work now.

**Comment by 1kastner** [comment]
now it works!
